<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Shay Abbasi">

<title>R, RStudio &amp; Quarto for Marketing Research</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="session-01-RLab_files/libs/clipboard/clipboard.min.js"></script>
<script src="session-01-RLab_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="session-01-RLab_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="session-01-RLab_files/libs/quarto-html/popper.min.js"></script>
<script src="session-01-RLab_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="session-01-RLab_files/libs/quarto-html/anchor.min.js"></script>
<link href="session-01-RLab_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="session-01-RLab_files/libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="session-01-RLab_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="session-01-RLab_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="session-01-RLab_files/libs/bootstrap/bootstrap-215b371544c282197b31c8aa00ce3677.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">R, RStudio &amp; Quarto for Marketing Research</h1>
<p class="subtitle lead">M731 Session 1 · R Basics and Exploratory Data Analysis on Maritime Roast Transactions</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Shay Abbasi </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="purpose-and-how-to-use-this-document" class="level2">
<h2 class="anchored" data-anchor-id="purpose-and-how-to-use-this-document">Purpose and how to use this document</h2>
<p>The slide deck (<code>session-01.qmd</code>) live-codes a short version of this material in class. This document is the <strong>full, self-contained teaching companion</strong>: it covers everything you need — RStudio, Quarto, and R basics through a first exploratory data analysis (EDA) — in one place, with real output and an interpretation after every step. Work through it at your own pace, ideally by typing the code yourself rather than copy-pasting, in a fresh <code>.qmd</code> file rendered in RStudio.</p>
<p>By the end you should be able to: read a CSV into R, inspect and understand what you loaded, derive new variables, find and fix common data-quality problems, summarise data numerically, and visualise it with <code>ggplot2</code> — the same five moves you will repeat, with fancier statistics layered on top, in every remaining session of this course.</p>
<p><strong>Dataset.</strong> <code>data/maritime_transactions.csv</code> is instructor-simulated: six months of Maritime Roast subscription orders, generated by <code>Sources/slides/data-raw/generate_datasets.R</code> with a fixed seed so it is exactly reproducible. It deliberately contains a handful of realistic data-quality problems — inconsistent category labels, duplicate rows, a few bad amounts, and legitimate missing values — so that the “cleaning data” section below has real work to do rather than a clean toy table with nothing to fix.</p>
</section>
<section id="working-in-rstudio" class="level1">
<h1>Working in RStudio</h1>
<p>You do not need to memorise this section — it is a reference for your first few weeks.</p>
<ul>
<li><strong>Source pane (top-left).</strong> Where you write and edit <code>.qmd</code> and <code>.R</code> files. Run the current line with <strong>Ctrl+Enter</strong> (Cmd+Return on Mac); run an entire code chunk with the green “play” arrow in its top-right corner, or <strong>Ctrl+Shift+Enter</strong>.</li>
<li><strong>Console (bottom-left).</strong> Where R actually evaluates code and prints results when you are working interactively, outside of a chunk.</li>
<li><strong>Environment pane (top-right).</strong> Lists every object currently in memory — every variable and data frame you have created. If a data frame you expect isn’t there, you probably haven’t run the chunk that creates it yet.</li>
<li><strong>Files / Plots / Packages / Help pane (bottom-right).</strong> Lets you browse the project folder, view the most recent plot, manage installed packages, and read function documentation (<code>?read_csv</code> opens the help page here).</li>
<li><strong>Render</strong> (Ctrl+Shift+K, or the “Render” button above the source pane) knits the whole <code>.qmd</code> file top to bottom into HTML, running every chunk in order in a fresh R session. If something only works because of a variable you created earlier and later deleted, Render will catch it even though “Run all chunks” might not.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>If RStudio’s <strong>Visual</strong> editor mode ever refuses to open a <code>.qmd</code> file with an error like “Error parsing code chunks out of document,” the usual cause is a code-fence character sequence appearing somewhere it shouldn’t (for example, demonstrating chunk syntax inside another code block). Switch to <strong>Source</strong> mode, fix the fence, and Visual mode will work again.</p>
</div>
</div>
</section>
<section id="working-in-quarto" class="level1">
<h1>Working in Quarto</h1>
<p>A <code>.qmd</code> file has three parts: a <strong>YAML header</strong> between <code>---</code> lines (controls the output format and document metadata), <strong>prose</strong> (ordinary Markdown), and <strong>code chunks</strong> (fenced with <code>```{r}</code> / <code>```</code>, containing R code that actually runs when the document renders). The “Anatomy of a .qmd file” slide in <code>session-01.qmd</code> shows this visually if you want the picture version.</p>
<p>Inside a chunk, <code>#|</code> lines set <strong>chunk options</strong> — settings for that specific chunk. The ones you’ll use constantly this term:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Option</th>
<th>Effect</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>label:</code></td>
<td>A short, unique name for the chunk (used in cross-references and error messages)</td>
</tr>
<tr class="even">
<td><code>echo:</code></td>
<td>Show the R code itself in the rendered output? (<code>true</code>/<code>false</code>)</td>
</tr>
<tr class="odd">
<td><code>eval:</code></td>
<td>Actually run the code? (<code>false</code> is useful for showing syntax you don’t want executed)</td>
</tr>
<tr class="even">
<td><code>warning:</code> / <code>message:</code></td>
<td>Suppress R’s warning/message text from cluttering the output</td>
</tr>
<tr class="odd">
<td><code>fig-width:</code> / <code>fig-height:</code></td>
<td>Size, in inches, of any plot the chunk produces</td>
</tr>
<tr class="even">
<td><code>fig-cap:</code></td>
<td>Caption text under a figure</td>
</tr>
</tbody>
</table>
<p>This document sets sensible defaults once, in the YAML header (<code>execute:</code> block above), so individual chunks below don’t repeat <code>echo</code>/<code>eval</code>/<code>warning</code>/<code>message</code> every time — only when a chunk needs to deviate from the default.</p>
</section>
<section id="setup" class="level1">
<h1>Setup</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><code>tidyverse</code> is a meta-package: loading it loads <code>readr</code> (reading data), <code>dplyr</code> (manipulating data), <code>ggplot2</code> (plotting), <code>stringr</code> (text cleaning), <code>lubridate</code> (dates), and several others in one line. This is the only <code>library()</code> call this document needs.</p>
</section>
<section id="r-basics-data-types" class="level1">
<h1>R Basics: Data Types</h1>
<p>Before touching a real dataset, it’s worth seeing R’s basic data types in isolation, because every column you load later will be one of these.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>a_number    <span class="ot">&lt;-</span> <span class="fl">15.99</span>                          <span class="co"># numeric (double)</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>a_count     <span class="ot">&lt;-</span> <span class="dv">3</span>L                             <span class="co"># integer</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>a_word      <span class="ot">&lt;-</span> <span class="st">"Standard"</span>                     <span class="co"># character</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>a_flag      <span class="ot">&lt;-</span> <span class="cn">TRUE</span>                           <span class="co"># logical</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>a_date      <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(<span class="st">"2026-01-01"</span>)          <span class="co"># Date</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>a_category  <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="st">"Signature"</span>,</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>                      <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Standard"</span>, <span class="st">"Signature"</span>, <span class="st">"Discovery"</span>))</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(a_number); <span class="fu">class</span>(a_count); <span class="fu">class</span>(a_word); <span class="fu">class</span>(a_flag); <span class="fu">class</span>(a_date); <span class="fu">class</span>(a_category)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "numeric"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "integer"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "character"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "logical"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Date"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "factor"</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">typeof</span>(a_count)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "integer"</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>a_count</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
</div>
<p><strong>Interpretation.</strong> <code>class()</code> tells you what R thinks a value <em>is</em>, which determines what you’re allowed to do with it — you can take the <code>mean()</code> of numbers, but not of characters; you can compare Dates with <code>&lt;</code> and <code>&gt;</code> to find “which order came first,” but comparing plain character strings that happen to look like dates (“2026-01-01” vs “2026-1-1”) can silently give the wrong answer. Getting column types right when you <em>read</em> data in is therefore not a formality — it’s the first data-quality check.</p>
<section id="vectors-the-building-block" class="level2">
<h2 class="anchored" data-anchor-id="vectors-the-building-block">Vectors — the building block</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>prices <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">15.99</span>, <span class="fl">22.50</span>, <span class="fl">18.75</span>, <span class="fl">25.00</span>, <span class="fl">19.99</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(prices)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 20.446</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(prices)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.460423</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(prices)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 19.99</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(prices)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 15.99</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(prices)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 25</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>subs <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Standard"</span>, <span class="st">"Discovery"</span>, <span class="st">"Discovery"</span>, <span class="st">"Signature"</span>, <span class="st">"Discovery"</span>, <span class="st">"Signature"</span>,<span class="st">"Signature"</span>, <span class="st">"Discovery"</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">typeof</span>(subs)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "character"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">typeof</span>(prices)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "double"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(prices)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "numeric"</code></pre>
</div>
</div>
<p><strong>Interpretation.</strong> Five prices average 20.45 dollars with a standard deviation of 3.46 — a tight, plausible spread for coffee-bag pricing across three tiers. R <em>vectorises</em> automatically: <code>prices * 1.13</code> would scale every price by 13% in one step, with no loop.</p>
</section>
<section id="data-frames-vectors-bundled-into-a-table" class="level2">
<h2 class="anchored" data-anchor-id="data-frames-vectors-bundled-into-a-table">Data frames — vectors bundled into a table</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>toy <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">tier   =</span> <span class="fu">c</span>(<span class="st">"Standard"</span>, <span class="st">"Signature"</span>, <span class="st">"Discovery"</span>),</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">price  =</span> <span class="fu">c</span>(<span class="fl">14.99</span>, <span class="fl">22.50</span>, <span class="fl">32.00</span>),</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">active =</span> <span class="fu">c</span>(<span class="cn">TRUE</span>, <span class="cn">TRUE</span>, <span class="cn">FALSE</span>)</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>toy</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       tier price active
1  Standard 14.99   TRUE
2 Signature 22.50   TRUE
3 Discovery 32.00  FALSE</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(toy)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   3 obs. of  3 variables:
 $ tier  : chr  "Standard" "Signature" "Discovery"
 $ price : num  15 22.5 32
 $ active: logi  TRUE TRUE FALSE</code></pre>
</div>
</div>
<p><strong>Interpretation.</strong> A data frame is a table where every column is a vector, all of the <em>same length</em>, but not necessarily the same type — here <code>tier</code> is character, <code>price</code> is numeric, <code>active</code> is logical. This is exactly the structure a CSV file becomes once you read it into R.</p>
</section>
</section>
<section id="reading-data" class="level1">
<h1>Reading Data</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>tx <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/maritime_transactions.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">spec</span>(tx)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>cols(
  order_id = col_double(),
  subscriber_id = col_double(),
  order_date = col_date(format = ""),
  tier = col_character(),
  region = col_character(),
  channel = col_character(),
  referral_source = col_character(),
  product_category = col_character(),
  bag_weight_g = col_double(),
  payment_method = col_character(),
  quantity = col_double(),
  unit_price = col_double(),
  discount_pct = col_double(),
  coupon_code = col_character(),
  free_shipping = col_logical(),
  shipping_cost = col_double(),
  amount = col_double(),
  delivery_days = col_double(),
  satisfaction_rating = col_double(),
  is_first_order = col_logical(),
  churn_flag = col_double()
)</code></pre>
</div>
</div>
<p><strong>Interpretation.</strong> <code>read_csv()</code> (from <code>readr</code>, part of <code>tidyverse</code>) guesses each column’s type from its first ~1,000 values and prints its guesses via <code>spec()</code> — this is worth reading once per new dataset. It correctly parsed <code>order_date</code> as a <code>Date</code> and <code>free_shipping</code> / <code>is_first_order</code> as logical, without being told to. Base R’s <code>read.csv()</code> would have left dates as plain character text, which is exactly the kind of silent type problem the previous section warned about.</p>
<section id="first-look" class="level2">
<h2 class="anchored" data-anchor-id="first-look">First look</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co">#glimpse(tx)</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="co">#dim(tx)</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(tx)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "order_id"            "subscriber_id"       "order_date"         
 [4] "tier"                "region"              "channel"            
 [7] "referral_source"     "product_category"    "bag_weight_g"       
[10] "payment_method"      "quantity"            "unit_price"         
[13] "discount_pct"        "coupon_code"         "free_shipping"      
[16] "shipping_cost"       "amount"              "delivery_days"      
[19] "satisfaction_rating" "is_first_order"      "churn_flag"         </code></pre>
</div>
</div>
<p><strong>Interpretation.</strong> 15040 rows across 21 columns. <code>glimpse()</code> is usually the very first function to run on a new dataset — it shows every column, its type, and its first few values in one screen, which <code>head()</code> cannot do once a table has more than a handful of columns.</p>
</section>
</section>
<section id="indexing" class="level1">
<h1>Indexing</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>tx<span class="sc">$</span>tier <span class="sc">|&gt;</span> <span class="fu">head</span>()          <span class="co"># one column, first values</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Standard"  "Signature" "Signature" "Standard"  "Standard"  "Signature"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>tx[<span class="dv">1</span>, ]                    <span class="co"># first row, all columns</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 21
  order_id subscriber_id order_date tier     region  channel referral_source
     &lt;dbl&gt;         &lt;dbl&gt; &lt;date&gt;     &lt;chr&gt;    &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;          
1        1          3886 2026-06-28 Standard Ontario Web     Organic        
# ℹ 14 more variables: product_category &lt;chr&gt;, bag_weight_g &lt;dbl&gt;,
#   payment_method &lt;chr&gt;, quantity &lt;dbl&gt;, unit_price &lt;dbl&gt;, discount_pct &lt;dbl&gt;,
#   coupon_code &lt;chr&gt;, free_shipping &lt;lgl&gt;, shipping_cost &lt;dbl&gt;, amount &lt;dbl&gt;,
#   delivery_days &lt;dbl&gt;, satisfaction_rating &lt;dbl&gt;, is_first_order &lt;lgl&gt;,
#   churn_flag &lt;dbl&gt;</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>tx[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, <span class="fu">c</span>(<span class="st">"tier"</span>, <span class="st">"amount"</span>)]          <span class="co"># first five values of one column</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  tier      amount
  &lt;chr&gt;      &lt;dbl&gt;
1 Standard    58.4
2 Signature   67.1
3 Signature   17.0
4 Standard    35.2
5 Standard    14.1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>tx <span class="sc">|&gt;</span> <span class="fu">filter</span>(tier <span class="sc">==</span> <span class="st">"Discovery"</span>) <span class="sc">|&gt;</span> <span class="fu">summarise</span>(<span class="at">mean_amount =</span> <span class="fu">mean</span>(amount), <span class="at">median_amount =</span> <span class="fu">median</span>(amount))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  mean_amount median_amount
        &lt;dbl&gt;         &lt;dbl&gt;
1        48.9          37.4</code></pre>
</div>
</div>
<p><strong>Interpretation.</strong> The pipe <code>|&gt;</code> reads left to right as “and then”: take <code>tx</code>, <em>and then</em> keep only Discovery-tier rows, <em>and then</em> summarise. Discovery-tier orders average more per order than the overall book, which makes sense — Discovery is the premium tier. (Notice this number is only approximately right at this point, because we haven’t cleaned the messy tier labels yet — more on that shortly.)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(tx<span class="sc">$</span>amount, )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="session-01-RLab_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="making-deriving-variables" class="level1">
<h1>Making (Deriving) Variables</h1>
<p>Raw columns are rarely the variables you actually want to analyse. <code>mutate()</code> adds new columns computed from existing ones.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>tx <span class="ot">&lt;-</span> tx <span class="sc">|&gt;</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">order_weekday   =</span> <span class="fu">wday</span>(order_date, <span class="at">label =</span> <span class="cn">TRUE</span>, <span class="at">abbr =</span> <span class="cn">FALSE</span>),</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">is_weekend      =</span> order_weekday <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Saturday"</span>, <span class="st">"Sunday"</span>),</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">order_size      =</span> <span class="fu">case_when</span>(</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>      quantity <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">"Single bag"</span>,</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>      quantity <span class="sc">==</span> <span class="dv">2</span> <span class="sc">~</span> <span class="st">"Two bags"</span>,</span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>      quantity <span class="sc">&gt;=</span> <span class="dv">3</span> <span class="sc">~</span> <span class="st">"Three or more"</span></span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">delivery_speed  =</span> <span class="fu">case_when</span>(</span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a>      delivery_days <span class="sc">&lt;=</span> <span class="dv">3</span>               <span class="sc">~</span> <span class="st">"Fast (&lt;=3 days)"</span>,</span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a>      delivery_days <span class="sc">&lt;=</span> <span class="dv">7</span>               <span class="sc">~</span> <span class="st">"Standard (4-7 days)"</span>,</span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a>      delivery_days <span class="sc">&gt;</span> <span class="dv">7</span>                <span class="sc">~</span> <span class="st">"Slow (&gt;7 days)"</span>,</span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span>                             <span class="sc">~</span> <span class="cn">NA_character_</span></span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a>    <span class="co"># a check, not just a convenience variable: does the recorded amount</span></span>
<span id="cb47-17"><a href="#cb47-17" aria-hidden="true" tabindex="-1"></a>    <span class="co"># match what price x quantity x discount + shipping implies? Note:</span></span>
<span id="cb47-18"><a href="#cb47-18" aria-hidden="true" tabindex="-1"></a>    <span class="co"># deliberately NOT coalescing missing shipping_cost to 0 -- if we</span></span>
<span id="cb47-19"><a href="#cb47-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># don't know the shipping fee, we can't verify the total, and the</span></span>
<span id="cb47-20"><a href="#cb47-20" aria-hidden="true" tabindex="-1"></a>    <span class="co"># check should honestly say "unknown" (NA) rather than guess.</span></span>
<span id="cb47-21"><a href="#cb47-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">expected_amount =</span> <span class="fu">round</span>(unit_price <span class="sc">*</span> quantity <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> discount_pct) <span class="sc">+</span> shipping_cost, <span class="dv">2</span>),</span>
<span id="cb47-22"><a href="#cb47-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">amount_gap      =</span> <span class="fu">round</span>(amount <span class="sc">-</span> expected_amount, <span class="dv">2</span>)</span>
<span id="cb47-23"><a href="#cb47-23" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb47-24"><a href="#cb47-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-25"><a href="#cb47-25" aria-hidden="true" tabindex="-1"></a>tx <span class="sc">|&gt;</span> <span class="fu">select</span>(order_id, order_weekday, is_weekend, order_size, delivery_speed, amount, expected_amount, amount_gap) <span class="sc">|&gt;</span> <span class="fu">head</span>(<span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 8
  order_id order_weekday is_weekend order_size    delivery_speed      amount
     &lt;dbl&gt; &lt;ord&gt;         &lt;lgl&gt;      &lt;chr&gt;         &lt;chr&gt;                &lt;dbl&gt;
1        1 Sunday        TRUE       Two bags      Standard (4-7 days)   58.4
2        2 Wednesday     FALSE      Three or more Standard (4-7 days)   67.1
3        3 Friday        FALSE      Single bag    Slow (&gt;7 days)        17.0
4        4 Monday        FALSE      Two bags      Slow (&gt;7 days)        35.2
5        5 Friday        FALSE      Single bag    Standard (4-7 days)   14.1
# ℹ 2 more variables: expected_amount &lt;dbl&gt;, amount_gap &lt;dbl&gt;</code></pre>
</div>
</div>
<p><strong>Interpretation.</strong> <code>order_weekday</code> and <code>is_weekend</code> come from <code>lubridate::wday()</code>, loaded automatically with <code>tidyverse</code>. <code>case_when()</code> is <code>mutate()</code>’s tool for “if this, then that, else…” bucketing — cleaner to read than nested <code>ifelse()</code> once you have more than two cases. <code>expected_amount</code> and <code>amount_gap</code> are the more important pattern here: <strong>recompute a value two independent ways and compare them</strong>. Most rows should show <code>amount_gap</code> at or near zero; rows where it doesn’t are exactly the data-entry errors the next section goes looking for. Rows with a missing <code>shipping_cost</code> get an <code>NA</code> <code>amount_gap</code> — that’s correct behaviour, not a bug: with an unknown input, R (correctly) refuses to guess whether the total is right, rather than silently assuming shipping was free. Substituting a 0 there (e.g.&nbsp;via <code>coalesce()</code>) would have manufactured 100+ false “errors” out of orders that were simply missing one unrelated field — a good example of how a cleaning <em>check</em> can itself introduce bias if you’re not careful about what a missing value actually means.</p>
</section>
<section id="cleaning-data" class="level1">
<h1>Cleaning Data</h1>
<p>Cleaning is not “delete anything that looks wrong.” It’s: <strong>find</strong> every issue, <strong>understand</strong> why it’s there, and <strong>decide</strong> — row by row or issue by issue — whether to fix it, flag it, or leave it and document why. This section works through four issue types found in <code>tx</code>.</p>
<section id="missing-values" class="level2">
<h2 class="anchored" data-anchor-id="missing-values">Missing values</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>tx <span class="sc">|&gt;</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(.)))) <span class="sc">|&gt;</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">everything</span>(), <span class="at">names_to =</span> <span class="st">"column"</span>, <span class="at">values_to =</span> <span class="st">"n_missing"</span>) <span class="sc">|&gt;</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(n_missing <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">|&gt;</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(n_missing))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 2
  column              n_missing
  &lt;chr&gt;                   &lt;int&gt;
1 satisfaction_rating      9782
2 delivery_days             451
3 delivery_speed            451
4 shipping_cost             301
5 expected_amount           301
6 amount_gap                301
7 subscriber_id              15</code></pre>
</div>
</div>
<p><strong>Interpretation.</strong> Three columns carry missing values, and each has a <em>different</em> reason — this matters, because the right response depends on the reason, not just the count:</p>
<ul>
<li><code>satisfaction_rating</code> is missing for most rows because only survey-responding customers have one. This is <strong>not a data error</strong> — it is a real, structural non-response pattern, and dropping those rows before any analysis involving satisfaction would silently bias the sample toward survey-responders. The correct move is usually to keep the <code>NA</code>s, use <code>na.rm = TRUE</code> in summaries, and report the response rate alongside the results.</li>
<li><code>delivery_days</code> is missing for orders not yet delivered as of the data pull — also structural, not an error, but worth footnoting in any delivery-time analysis.</li>
<li><code>shipping_cost</code> missing values look like a genuine sync glitch between the order system and the shipping system — a smaller number of rows, no obvious pattern, worth flagging to whoever owns that data pipeline rather than silently imputing a number.</li>
<li><code>subscriber_id</code> missing on a handful of rows represents guest checkouts never linked to an account — expected in an e-commerce system, not an error, but it does mean those rows can’t be used in any <em>subscriber-level</em> (as opposed to <em>order-level</em>) analysis.</li>
</ul>
</section>
<section id="inconsistent-category-labels" class="level2">
<h2 class="anchored" data-anchor-id="inconsistent-category-labels">Inconsistent category labels</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>tx <span class="sc">|&gt;</span> <span class="fu">count</span>(tier, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
  tier          n
  &lt;chr&gt;     &lt;int&gt;
1 Standard   8325
2 Signature  4541
3 Discovery  2137
4 SIGNATURE    16
5 discovery    11
6 standard     10</code></pre>
</div>
</div>
<p><strong>Interpretation.</strong> <code>tier</code> should have exactly three values, but whitespace and capitalization inconsistencies (” standard”, “SIGNATURE”, “discovery”, etc.) have split it into more. This is one of the most common real-world data problems — the same underlying category entered inconsistently by different systems or people. Fix with <code>str_squish()</code> (trims and collapses whitespace) and <code>str_to_title()</code> (standardises capitalisation):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>tx <span class="ot">&lt;-</span> tx <span class="sc">|&gt;</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">tier =</span> <span class="fu">str_to_title</span>(<span class="fu">str_squish</span>(tier)))</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>tx <span class="sc">|&gt;</span> <span class="fu">count</span>(tier, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  tier          n
  &lt;chr&gt;     &lt;int&gt;
1 Standard   8335
2 Signature  4557
3 Discovery  2148</code></pre>
</div>
</div>
<p><strong>Interpretation.</strong> Three clean tier levels, as expected. Always re-run the check (<code>count()</code>) immediately after a cleaning step — never assume the fix worked.</p>
</section>
<section id="duplicate-rows" class="level2">
<h2 class="anchored" data-anchor-id="duplicate-rows">Duplicate rows</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>n_before <span class="ot">&lt;-</span> <span class="fu">nrow</span>(tx)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>n_duplicate_rows <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">duplicated</span>(tx))</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>n_duplicate_rows</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 39</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>tx <span class="ot">&lt;-</span> tx <span class="sc">|&gt;</span> <span class="fu">distinct</span>()</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>n_after <span class="ot">&lt;-</span> <span class="fu">nrow</span>(tx)</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(n_before, n_duplicate_rows, n_after)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  n_before n_duplicate_rows n_after
     &lt;int&gt;            &lt;int&gt;   &lt;int&gt;
1    15040               39   15001</code></pre>
</div>
</div>
<p><strong>Interpretation.</strong> <code>duplicated()</code> flags rows that are an <em>exact</em> repeat of an earlier row (every column identical) — consistent with a sync or export glitch that wrote the same order twice, not with two genuinely different orders that happen to share some values. <code>distinct()</code> keeps one copy of each. As with any cleaning step, report the before/after row counts explicitly rather than silently changing the data.</p>
</section>
<section id="outliers-and-data-entry-errors" class="level2">
<h2 class="anchored" data-anchor-id="outliers-and-data-entry-errors">Outliers and data-entry errors</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(tx, <span class="fu">aes</span>(<span class="at">x =</span> tier, <span class="at">y =</span> amount, <span class="at">fill =</span> tier)) <span class="sc">+</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">outlier.color =</span> <span class="st">"firebrick"</span>, <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Tier"</span>, <span class="at">y =</span> <span class="st">"Order amount ($)"</span>) <span class="sc">+</span></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="session-01-RLab_files/figure-html/outlier-boxplot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Order amount by tier, before outlier handling</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation.</strong> A handful of points sit far outside the whiskers — some negative, some implausibly large. Negative order amounts and amounts several multiples of a normal order are not “unusually generous customers”; they’re the signature of a data-entry problem (a refund miscoded as a charge, a quantity typo). Confirm with the <code>amount_gap</code> check built earlier, then flag rather than silently drop:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>tx <span class="ot">&lt;-</span> tx <span class="sc">|&gt;</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">amount_flag =</span> <span class="fu">case_when</span>(</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>      amount <span class="sc">&lt;</span> <span class="dv">0</span>                    <span class="sc">~</span> <span class="st">"Negative amount"</span>,</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">abs</span>(amount_gap) <span class="sc">&gt;</span> <span class="dv">5</span>           <span class="sc">~</span> <span class="st">"Amount does not match price x qty"</span>,</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span>                          <span class="sc">~</span> <span class="cn">NA_character_</span></span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a>tx <span class="sc">|&gt;</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(amount_flag)) <span class="sc">|&gt;</span> <span class="fu">select</span>(order_id, tier, quantity, unit_price, discount_pct, shipping_cost, amount, expected_amount, amount_flag)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 9
   order_id tier      quantity unit_price discount_pct shipping_cost amount
      &lt;dbl&gt; &lt;chr&gt;        &lt;dbl&gt;      &lt;dbl&gt;        &lt;dbl&gt;         &lt;dbl&gt;  &lt;dbl&gt;
 1      850 Standard         1      27.7          0             4.99  262. 
 2     1613 Standard         1      29.1          0             4.99  411. 
 3     2481 Standard         1      15.0          0.1           4.99  -18.4
 4     3411 Signature        3      41.6          0             0    -125. 
 5     3781 Standard         1      15.0          0             4.99  221. 
 6     4364 Standard         1      27.7          0             4.99  261. 
 7     9203 Standard         1      15.0          0             4.99  -19.9
 8     9277 Standard         2      29.1          0             0     -58.6
 9     9970 Standard         1       8.99         0             4.99  184. 
10    12675 Standard         1      15.0          0.15          4.99  -17.7
11    13225 Signature        1      13.5          0             4.99  -18.3
12    14073 Standard         2      15.0          0             4.99  280. 
# ℹ 2 more variables: expected_amount &lt;dbl&gt;, amount_flag &lt;chr&gt;</code></pre>
</div>
</div>
<p><strong>Interpretation.</strong> Flagging (adding a column that marks the problem) rather than deleting preserves the row for anyone downstream who wants to see exactly what was excluded and why — a written analysis should always be able to say “N rows were excluded for reason X,” never just present a smaller, unexplained row count. For the descriptive and visual analysis in the rest of this document, we now exclude the flagged rows:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>tx_clean <span class="ot">&lt;-</span> tx <span class="sc">|&gt;</span> <span class="fu">filter</span>(<span class="fu">is.na</span>(amount_flag))</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(tx); <span class="fu">nrow</span>(tx_clean)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 15001</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 14989</code></pre>
</div>
</div>
<p><strong>Interpretation.</strong> 12 rows excluded out of 15001 — a tiny fraction of the dataset, which is exactly what you’d expect from a real (as opposed to catastrophically broken) data source. <code>tx_clean</code> is what the rest of this document uses.</p>
</section>
</section>
<section id="exploratory-data-analysis-descriptives" class="level1">
<h1>Exploratory Data Analysis: Descriptives</h1>
<section id="overall-summary" class="level2">
<h2 class="anchored" data-anchor-id="overall-summary">Overall summary</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(tx_clean<span class="sc">$</span>amount)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  11.84   19.89   27.49   31.97   37.03  186.69 </code></pre>
</div>
</div>
<p><strong>Interpretation.</strong> <code>summary()</code> gives min, quartiles, mean, and max in one call — a fast sanity check before any grouped analysis. The median sitting below the mean signals a right-skewed distribution (a few large orders pull the average up), which the histogram below will show directly.</p>
</section>
<section id="grouped-descriptives-with-dplyr" class="level2">
<h2 class="anchored" data-anchor-id="grouped-descriptives-with-dplyr">Grouped descriptives with dplyr</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>tx_summary <span class="ot">&lt;-</span> tx_clean <span class="sc">|&gt;</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(tier, region) <span class="sc">|&gt;</span></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">n             =</span> <span class="fu">n</span>(),</span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_amount   =</span> <span class="fu">mean</span>(amount),</span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">median_amount =</span> <span class="fu">median</span>(amount),</span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">total         =</span> <span class="fu">sum</span>(amount),</span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups       =</span> <span class="st">"drop"</span></span>
<span id="cb67-9"><a href="#cb67-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb67-10"><a href="#cb67-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(mean_amount))</span>
<span id="cb67-11"><a href="#cb67-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-12"><a href="#cb67-12" aria-hidden="true" tabindex="-1"></a>tx_summary</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 6
  tier      region       n mean_amount median_amount   total
  &lt;chr&gt;     &lt;chr&gt;    &lt;int&gt;       &lt;dbl&gt;         &lt;dbl&gt;   &lt;dbl&gt;
1 Discovery Ontario    415        49.2          38.7  20398.
2 Discovery Atlantic  1726        48.7          37.1  84113.
3 Signature Ontario    879        36.1          28.7  31738.
4 Signature Atlantic  3667        34.9          27.6 128142.
5 Standard  Ontario   1695        27.2          20.9  46106.
6 Standard  Atlantic  6607        25.5          20.1 168768.</code></pre>
</div>
</div>
<p><strong>Interpretation.</strong> Read this table by scanning <code>mean_amount</code> top to bottom. Discovery orders carry the highest average order value in both regions; Ontario orders run slightly above Atlantic orders within each tier, consistent with the small Ontario price adjustment built into the simulation. This is exactly the sort of table you’d open a client memo with — one paragraph on “who spends the most” answers itself from this output alone.</p>
</section>
<section id="a-first-look-at-churn" class="level2">
<h2 class="anchored" data-anchor-id="a-first-look-at-churn">A first look at churn</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>tx_clean <span class="sc">|&gt;</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(tier) <span class="sc">|&gt;</span></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">n_orders    =</span> <span class="fu">n</span>(),</span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">churn_rate  =</span> <span class="fu">mean</span>(churn_flag),</span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups     =</span> <span class="st">"drop"</span></span>
<span id="cb69-7"><a href="#cb69-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb69-8"><a href="#cb69-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(churn_rate))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  tier      n_orders churn_rate
  &lt;chr&gt;        &lt;int&gt;      &lt;dbl&gt;
1 Standard      8302      0.270
2 Signature     4546      0.187
3 Discovery     2141      0.142</code></pre>
</div>
</div>
<p><strong>Interpretation.</strong> Standard-tier orders show the highest churn-flag rate, Discovery the lowest — a pattern worth carrying into the Week 6 hypothesis-testing lab, where we test whether WTP and satisfaction differ meaningfully by subscriber status.</p>
</section>
<section id="cross-tabulating-two-categorical-variables" class="level2">
<h2 class="anchored" data-anchor-id="cross-tabulating-two-categorical-variables">Cross-tabulating two categorical variables</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>tx_clean <span class="sc">|&gt;</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(channel, tier) <span class="sc">|&gt;</span></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> tier, <span class="at">values_from =</span> n, <span class="at">values_fill =</span> <span class="dv">0</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 4
  channel        Discovery Signature Standard
  &lt;chr&gt;              &lt;int&gt;     &lt;int&gt;    &lt;int&gt;
1 Mobile_app           641      1307     2517
2 Retail_partner       346       637     1195
3 Web                 1154      2602     4590</code></pre>
</div>
</div>
<p><strong>Interpretation.</strong> <code>count()</code> + <code>pivot_wider()</code> turns two categorical columns into a familiar cross-tab shape. Retail-partner orders lean toward different tiers than Web/Mobile-app orders — worth a follow-up question about whether that reflects what physical grocers choose to stock, or a genuinely different customer.</p>
</section>
</section>
<section id="visualizing-data-with-ggplot2" class="level1">
<h1>Visualizing Data with ggplot2</h1>
<p>Every <code>ggplot2</code> plot follows the same recipe: <code>ggplot(data, aes(...))</code> sets up <em>what</em> maps to <em>where</em>, then one or more <code>geom_*()</code> layers say <em>how</em> to draw it.</p>
<section id="distribution-histogram" class="level2">
<h2 class="anchored" data-anchor-id="distribution-histogram">Distribution: histogram</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(tx_clean, <span class="fu">aes</span>(<span class="at">x =</span> amount)) <span class="sc">+</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">2</span>, <span class="at">fill =</span> <span class="st">"#7A003C"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Order amount ($)"</span>, <span class="at">y =</span> <span class="st">"Number of orders"</span>) <span class="sc">+</span></span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="session-01-RLab_files/figure-html/hist-amount-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Distribution of order amount (cleaned data)</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation.</strong> The right-skew flagged by <code>summary()</code> is visible directly: most orders cluster in a normal range, with a thinning tail of larger multi-bag or Discovery-tier orders.</p>
</section>
<section id="comparison-across-groups-boxplot" class="level2">
<h2 class="anchored" data-anchor-id="comparison-across-groups-boxplot">Comparison across groups: boxplot</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(tx_clean, <span class="fu">aes</span>(<span class="at">x =</span> tier, <span class="at">y =</span> amount, <span class="at">fill =</span> tier)) <span class="sc">+</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Tier"</span>, <span class="at">y =</span> <span class="st">"Order amount ($)"</span>) <span class="sc">+</span></span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="session-01-RLab_files/figure-html/box-amount-clean-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Order amount by tier, after cleaning</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation.</strong> Compare this to the “before” boxplot in the outlier section — the extreme points are gone, and the three tiers’ typical price ranges are now visually well-separated and plausible.</p>
</section>
<section id="counts-bar-chart" class="level2">
<h2 class="anchored" data-anchor-id="counts-bar-chart">Counts: bar chart</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>tx_clean <span class="sc">|&gt;</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(channel) <span class="sc">|&gt;</span></span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fct_reorder</span>(channel, n), <span class="at">y =</span> n, <span class="at">fill =</span> channel)) <span class="sc">+</span></span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Number of orders"</span>) <span class="sc">+</span></span>
<span id="cb75-7"><a href="#cb75-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="session-01-RLab_files/figure-html/bar-channel-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Orders by acquisition channel</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation.</strong> <code>fct_reorder()</code> sorts the bars by count instead of alphabetically — a small habit that makes almost every bar chart easier to read at a glance.</p>
</section>
<section id="trend-over-time-line-chart" class="level2">
<h2 class="anchored" data-anchor-id="trend-over-time-line-chart">Trend over time: line chart</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>tx_clean <span class="sc">|&gt;</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(order_date) <span class="sc">|&gt;</span></span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">daily_revenue =</span> <span class="fu">sum</span>(amount), <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">|&gt;</span></span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> order_date, <span class="at">y =</span> daily_revenue)) <span class="sc">+</span></span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"#7A003C"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"#FDBF57"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Revenue ($)"</span>) <span class="sc">+</span></span>
<span id="cb76-8"><a href="#cb76-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="session-01-RLab_files/figure-html/line-daily-revenue-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Daily revenue, six-month window</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation.</strong> The thin line is noisy day-to-day revenue; the smoothed trend line (<code>geom_smooth()</code>) makes any underlying drift easier to see through the noise — the same logic behind every “trend line” you’ve seen on a business dashboard.</p>
</section>
<section id="small-multiples-faceting" class="level2">
<h2 class="anchored" data-anchor-id="small-multiples-faceting">Small multiples: faceting</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>tx_clean <span class="sc">|&gt;</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">order_week =</span> <span class="fu">floor_date</span>(order_date, <span class="st">"week"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(order_week, tier) <span class="sc">|&gt;</span></span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">weekly_revenue =</span> <span class="fu">sum</span>(amount), <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">|&gt;</span></span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> order_week, <span class="at">y =</span> weekly_revenue, <span class="at">color =</span> tier)) <span class="sc">+</span></span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb77-7"><a href="#cb77-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>tier, <span class="at">ncol =</span> <span class="dv">1</span>, <span class="at">scales =</span> <span class="st">"free_y"</span>) <span class="sc">+</span></span>
<span id="cb77-8"><a href="#cb77-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Revenue ($)"</span>, <span class="at">color =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb77-9"><a href="#cb77-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="session-01-RLab_files/figure-html/facet-tier-time-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Weekly revenue by tier</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation.</strong> <code>facet_wrap()</code> splits one plot into a small-multiple grid — one panel per tier — so you can compare each tier’s trend on its own scale without three overlapping, hard-to-read lines on a single panel.</p>
</section>
</section>
<section id="putting-it-together" class="level1">
<h1>Putting It Together</h1>
<p>Maritime Roast’s Standard tier generates the most orders but the lowest average order value and the highest churn-flag rate; Discovery is the opposite on all three counts. Combined with the acquisition channel table, this suggests two different customer motions worth separate marketing treatment — a high-volume, price-sensitive Standard segment and a smaller, higher-value, more loyal Discovery segment — rather than one blended “average subscriber” strategy. This is the kind of one-paragraph, decision-relevant conclusion every EDA in this course should end with: not just tables and plots, but what they imply for a specific business choice.</p>
</section>
<section id="take-away" class="level1">
<h1>Take-Away</h1>
<p>The pattern in every section above is the same five-step loop:</p>
<ol type="1">
<li><strong>Read</strong> the data and check what you actually got (<code>glimpse()</code>, <code>spec()</code>).</li>
<li><strong>Derive</strong> the variables you actually need (<code>mutate()</code>, <code>case_when()</code>).</li>
<li><strong>Clean</strong>, deliberately and visibly — find issues, understand them, decide, and document what you did (<code>count()</code>, <code>duplicated()</code>, boxplots, flag-don’t-silently-delete).</li>
<li><strong>Describe</strong> numerically (<code>summary()</code>, <code>group_by()</code> + <code>summarise()</code>).</li>
<li><strong>Visualise</strong> to see what the numbers alone hide (<code>ggplot2</code>).</li>
</ol>
<p>If you can run this loop from memory on a new dataset, you’re ready for Week 2.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>